/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Alias */

#ifndef _Included_Alias
#define _Included_Alias
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Alias
 * Method:    addAlias
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Alias_addAlias
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Alias
 * Method:    removeAlias
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Alias_removeAlias
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
