/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: load-dir/cs.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.test.cdb2.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module cs.yang */
public class cs extends ConfNamespace {
    public static final int hash = 1968793414;
    public int hash() {
        return cs.hash;
    }

    public static final String id = "http://tail-f.com/test/cs";
    public String id() {
        return cs.id;
    }

    public static final String uri = "http://tail-f.com/test/cs/1.0";
    public String uri() {
        return cs.uri;
    }

    public static final String prefix = "cs";
    public String prefix() {
        return cs.prefix;
    }

    public cs() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _number = 146471600;
    public static final String _number_ = "number";
    public static final int    _maybe = 1965101911;
    public static final String _maybe_ = "maybe";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _operands = 1287603549;
    public static final String _operands_ = "operands";
    public static final int    _computer = 27910163;
    public static final String _computer_ = "computer";
    public static final int    _math = 446880983;
    public static final String _math_ = "math";
    public static final int    _operation = 1037011282;
    public static final String _operation_ = "operation";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _system = 1534086422;
    public static final String _system_ = "system";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final String actionpoint_math_cs = "math_cs";
}
