/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: load-dir/zub.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.test.cdb2.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module zub.yang */
public class zub extends ConfNamespace {
    public static final int hash = 1239930951;
    public int hash() {
        return zub.hash;
    }

    public static final String id = "http://acme.com/zub";
    public String id() {
        return zub.id;
    }

    public static final String uri = "http://acme.com/zub";
    public String uri() {
        return zub.uri;
    }

    public static final String prefix = "zb";
    public String prefix() {
        return zub.prefix;
    }

    public zub() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _queueDisciplines = 982210113;
    public static final String _queueDisciplines_ = "queueDisciplines";
    public static final int    _b = 554582006;
    public static final String _b_ = "b";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _hosts = 756968979;
    public static final String _hosts_ = "hosts";
    public static final int    _LOOPBACK = 1356692305;
    public static final String _LOOPBACK_ = "LOOPBACK";
    public static final int    _host = 1711485895;
    public static final String _host_ = "host";
    public static final int    _keyless_list = 763435237;
    public static final String _keyless_list_ = "keyless-list";
    public static final int    _number = 146471600;
    public static final String _number_ = "number";
    public static final int    _port = 10387472;
    public static final String _port_ = "port";
    public static final int    _foobar = 89781437;
    public static final String _foobar_ = "foobar";
    public static final int    _zconfigzub = 342461173;
    public static final String _zconfigzub_ = "zconfigzub";
    public static final int    _only10Mbps = 2097478362;
    public static final String _only10Mbps_ = "only10Mbps";
    public static final int    _addr = 1376787785;
    public static final String _addr_ = "addr";
    public static final int    _ip = 1643785435;
    public static final String _ip_ = "ip";
    public static final int    _ident_type_child3 = 272692236;
    public static final String _ident_type_child3_ = "ident-type-child3";
    public static final int    _maybe = 1965101911;
    public static final String _maybe_ = "maybe";
    public static final int    _burka = 1027244289;
    public static final String _burka_ = "burka";
    public static final int    _v2 = 658749087;
    public static final String _v2_ = "v2";
    public static final int    _validate_servers = 233069812;
    public static final String _validate_servers_ = "validate-servers";
    public static final int    _srv_name = 1765574596;
    public static final String _srv_name_ = "srv-name";
    public static final int    _brd = 1605308471;
    public static final String _brd_ = "brd";
    public static final int    _nils = 256745552;
    public static final String _nils_ = "nils";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _servers_3keys = 671127291;
    public static final String _servers_3keys_ = "servers-3keys";
    public static final int    _defaultLink = 2097540760;
    public static final String _defaultLink_ = "defaultLink";
    public static final int    _ident_type_child2 = 725816019;
    public static final String _ident_type_child2_ = "ident-type-child2";
    public static final int    _buzz = 1401841201;
    public static final String _buzz_ = "buzz";
    public static final int    _pres_foo = 1279807118;
    public static final String _pres_foo_ = "pres-foo";
    public static final int    _length = 1686396929;
    public static final String _length_ = "length";
    public static final int    _servers = 1403078918;
    public static final String _servers_ = "servers";
    public static final int    _ident_type = 1020753720;
    public static final String _ident_type_ = "ident-type";
    public static final int    _ident_type_child1 = 777349279;
    public static final String _ident_type_child1_ = "ident-type-child1";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _operands = 1287603549;
    public static final String _operands_ = "operands";
    public static final int    _link = 481374722;
    public static final String _link_ = "link";
    public static final int    _server_host = 1572770247;
    public static final String _server_host_ = "server-host";
    public static final int    _indexes = 616399475;
    public static final String _indexes_ = "indexes";
    public static final int    _sutate = 1642447190;
    public static final String _sutate_ = "sutate";
    public static final int    _linkLimitation = 1864339420;
    public static final String _linkLimitation_ = "linkLimitation";
    public static final int    _limitations = 991991763;
    public static final String _limitations_ = "limitations";
    public static final int    _ips = 136840998;
    public static final String _ips_ = "ips";
    public static final int    _computer = 27910163;
    public static final String _computer_ = "computer";
    public static final int    _bar = 230304278;
    public static final String _bar_ = "bar";
    public static final int    _baz = 882652968;
    public static final String _baz_ = "baz";
    public static final int    _flags = 1646628167;
    public static final String _flags_ = "flags";
    public static final int    _bay = 228459423;
    public static final String _bay_ = "bay";
    public static final int    _keyless_sublist = 713633124;
    public static final String _keyless_sublist_ = "keyless-sublist";
    public static final int    _k = 1590930917;
    public static final String _k_ = "k";
    public static final int    _onlyHalfDuplex = 989238434;
    public static final String _onlyHalfDuplex_ = "onlyHalfDuplex";
    public static final int    _x = 1735967608;
    public static final String _x_ = "x";
    public static final int    _UP = 82258393;
    public static final String _UP_ = "UP";
    public static final int    _keylezz = 170970002;
    public static final String _keylezz_ = "keylezz";
    public static final int    _buzz_interfaces = 1370888566;
    public static final String _buzz_interfaces_ = "buzz-interfaces";
    public static final int    _math = 446880983;
    public static final String _math_ = "math";
    public static final int    _server_ip = 1434589413;
    public static final String _server_ip_ = "server-ip";
    public static final int    _stats = 1979611730;
    public static final String _stats_ = "stats";
    public static final int    _operation = 1037011282;
    public static final String _operation_ = "operation";
    public static final int    _BROADCAST = 1616991328;
    public static final String _BROADCAST_ = "BROADCAST";
    public static final int    _if_name = 574639869;
    public static final String _if_name_ = "if-name";
    public static final int    _queueDiscipline = 1702267991;
    public static final String _queueDiscipline_ = "queueDiscipline";
    public static final int    _server = 163548884;
    public static final String _server_ = "server";
    public static final int    _ports = 1554580266;
    public static final String _ports_ = "ports";
    public static final int    _v3 = 1875892236;
    public static final String _v3_ = "v3";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _sub_keyless_container = 1428288734;
    public static final String _sub_keyless_container_ = "sub-keyless-container";
    public static final int    _foo = 161968632;
    public static final String _foo_ = "foo";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _v1 = 1223356638;
    public static final String _v1_ = "v1";
    public static final int    _ffoo = 2078170149;
    public static final String _ffoo_ = "ffoo";
    public static final int    _links = 159989304;
    public static final String _links_ = "links";
    public static final int    _keyless = 1043440335;
    public static final String _keyless_ = "keyless";
    public static final int    _NOTRAILERS = 1410096585;
    public static final String _NOTRAILERS_ = "NOTRAILERS";
    public static final int    _user_ports = 1714359059;
    public static final String _user_ports_ = "user-ports";
    public static final int    _main_ip = 558595535;
    public static final String _main_ip_ = "main-ip";
    public static final int    _linkLimitations = 17936018;
    public static final String _linkLimitations_ = "linkLimitations";
    public static final int    _MULTICAST = 146719160;
    public static final String _MULTICAST_ = "MULTICAST";
    public static final int    _spink = 1163692790;
    public static final String _spink_ = "spink";
    public static final int    _system = 1534086422;
    public static final String _system_ = "system";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _linkName = 691083791;
    public static final String _linkName_ = "linkName";
    public static final int    _a = 1589197455;
    public static final String _a_ = "a";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _NOARP = 250325439;
    public static final String _NOARP_ = "NOARP";
    public static final int    _main_port = 794592514;
    public static final String _main_port_ = "main-port";
    public static final String actionpoint_math_cs = "math_cs";
    public static final String validate_validateIp = "validateIp";
    public static final String validate_validatePort = "validatePort";
}
