/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: load-dir/ha-controller-lite.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _HA_CONTROLLER_LITE_H_
#define _HA_CONTROLLER_LITE_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef hcl__ns
#define hcl__ns 1954060499
#define hcl__ns_id "http://tail-f.com/ns/ha-controller-lite"
#define hcl__ns_uri "http://tail-f.com/ns/ha-controller-lite"
#endif

#define hcl_ha_controller_lite 436032754
#define hcl_port 10387472
#define hcl_ha_nodes 1269240464
#define hcl_name 1998270519
#define hcl_preferred_master 1425584198
#define hcl_ip_address 36594129
#define hcl_ha_node 951862701
#define hcl_address 1266954393
#define hcl_secret_token 743506203
#define hcl_virtual_address 1031903216

#ifdef __cplusplus
}
#endif

#endif
